// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4sZ2qcVHG2yARbH_vjZSqR99xoSKNdtk',
    appId: '1:647956529851:web:9ef485432ee8c40c879f9e',
    messagingSenderId: '647956529851',
    projectId: 'kindride-user',
    authDomain: 'kindride-user.firebaseapp.com',
    storageBucket: 'kindride-user.appspot.com',
    measurementId: 'G-J7KV5P4V52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALTJva-MhzoND8lvXhasAON0StkblNZy8',
    appId: '1:647956529851:android:b43c4fee31b8ce8d879f9e',
    messagingSenderId: '647956529851',
    projectId: 'kindride-user',
    storageBucket: 'kindride-user.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeMgZfDlaOo3b572Fj97mQCbpFJqWW8eg',
    appId: '1:647956529851:ios:4e86a3a0770eadec879f9e',
    messagingSenderId: '647956529851',
    projectId: 'kindride-user',
    storageBucket: 'kindride-user.appspot.com',
    iosClientId:
        '647956529851-s7bhf7f5phlfv1j3re54niv7pe4sf1rk.apps.googleusercontent.com',
    iosBundleId: 'com.example.kindRides',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeMgZfDlaOo3b572Fj97mQCbpFJqWW8eg',
    appId: '1:647956529851:ios:4e86a3a0770eadec879f9e',
    messagingSenderId: '647956529851',
    projectId: 'kindride-user',
    storageBucket: 'kindride-user.appspot.com',
    iosClientId:
        '647956529851-s7bhf7f5phlfv1j3re54niv7pe4sf1rk.apps.googleusercontent.com',
    iosBundleId: 'com.example.kindRides',
  );
}
